# Configuração da aplicação
spring.application.name=gerenciamento-eventos
server.port=8080

# Configuração do H2 (banco em memória)
spring.datasource.url=jdbc:h2:mem:eventosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilita o console do H2 (acesse em http://localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostrar SQL no console (opcional para debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuração do Swagger UI (path customizado opcional)
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs