# ============================================================
# Aplicação
# ============================================================
spring.application.name=gerenciamento-eventos
server.port=8080

# ============================================================
# H2 (banco em memória)
# ============================================================
spring.datasource.url=jdbc:h2:mem:eventosdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ============================================================
# JPA ? Debug
# ============================================================
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ============================================================
# Swagger / OpenAPI
# ============================================================
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

# Ordenação alfabética
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.docExpansion=full

# Interatividade
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.displayRequestDuration=true

# Esconde a seção de schemas (models) do rodapé
springdoc.swagger-ui.defaultModelsExpandDepth=-1

# CSS customizado
springdoc.swagger-ui.custom-css=/swagger-custom.css